### ISSUE TITLE
Does not working with v1.23

### ISSUE THREAD

**Issue by Tej-Singh-Rana** [stackrox/admission-controller-webhook-demo#14]
I tested out with the Kubernetes version 1.23 and didn't work. Could you please check this? 
**Note: -** MutatingWebhookConfiguration API version has been changed "admissionregistration.k8s.io/v1beta1" to "admissionregistration.k8s.io/v1". 

Regards,

**Comment by TzlilSwimmer123** [comment]
Hi @Tej-Singh-Rana,
You need to change the manifest of `MutatingWebhookConfiguration` to be `apiVersion: admissionregistration.k8s.io/v1` and `admissionReviewVersions` to be `v1`.
The new K8s versions are using `admissionregistration.k8s.io/v1` and not the beta one.

Can you please share if creating all the resources together worked fine? I am facing a problem where the pod and deployment are stuck if I create the Deployment, Service and webhook together and not separated

**Comment by Tej-Singh-Rana** [comment]
Hi @TzlilSwimmer123 ,
Yeah, it worked after changing the api version `admissionregistration.k8s.io/v1beta1` to `admissionregistration.k8s.io/v1` and 
`admissionReviewVersions: ["v1", "v1beta1"]` to `admissionReviewVersions: ["v1beta1"]`.

Regards,
